### ISSUE TITLE
Rscripts fail to generate heatmap images

### ISSUE THREAD

**Issue by aghozlane** [GATB/simka#1]
Hi
I have made a simple comparison between two fasta files. Simka performed well, here is one of the matrix files : 

;id1;id2
id1;0.000000;0.991121
id2;0.991121;0.000000

but the scripts fail to create the heatmaps : 
`
python create_heatmaps.py  ../build/bin/test.txt/
`

Error in graphics:::plotHclust(n1, merge, height, order(x$order), hang,  :
  entrée de dendrogramme incorrecte
Calls: plot -> plot.hclust -> <Anonymous>
Exécution arrêtée

Second question :
Concerning the results, is it a factor or a percentage ?

Thanks for the help.

**Comment by GatouResearch** [comment]
Hi,

Values in the distance matrices are between 0 (similar) to 1 (dissimilar)

About error in heatmap, maybe you should try tu update your R version. Or try to pick a more recent version of Simka. We update this script recently.

**Comment by Bubus555** [comment]
I'm not sure but I assume that SIMKA is not abble to create heatmaps if you compare only 2 datasets actually but maybe I'm wrong.. Did you try to compare a least 3 datasets?

**Comment by GatouResearch** [comment]
Heatmaps are still working with 2 datasets, but in fact dendrogram generation failed.
It works perfectly well with at least 3 datasets
