### ISSUE TITLE
Job does not end

### ISSUE THREAD

**Issue by martialbriand** [GATB/simka#10]
Sometimes, especially when we have a lot of input files, the job stops at the merge stage (v1.3.2 and v1.4.0).

**Comment by nick-youngblut** [comment]
I'm using v1.5.1 and am running into the same issue. For instance, the end of the output on my last stalled run was:

```
83.3 %   elapsed:   0 min 6  sec   remaining:   0 min 1  sec   cpu:   0.5 %   mem: [  17,   17,   17] MB
```

The job stalled there until I killed it many hours later. The number of input files is 26, so I'm surprised that simka is having a problem. I'm running simka with the following params:

```
simka -kmer-size 31 -abundance-min 2 -simple-dist -max-reads 1000000 -nb-cores 24 -max-count 24 -max-merge 24 -max-memory 176 -in simka_input.txt -out ./simka/matrices/ -out-tmp ./simka/tmp/
```

Machine: `Ubuntu 18.04.3 LTS` with 1Tb of memory

**Comment by rchikhi** [comment]
hi, please try with a larger `-max-memory`, perhaps 50000

**Comment by nick-youngblut** [comment]
Larger `-max-memory` works, but it's the fact that simka freezes instead of dies with a non-zero exit. I have to try and create a time-out error for running simka to deal with this freezing issue.

**Comment by rchikhi** [comment]
Sorry, just to clarify: a larger -max-memory resulted in a successful run, which effectively solved your problem. Yet when running simka with very low max memory, it freezes. Is that accurate?

**Comment by nick-youngblut** [comment]
Yes. The problem with software freezing instead of throwing an error is that the user doesn't know that there's a problem without manually checking & also knowing about this "low memory causes freezing" issue. It's not optimal, especially for new users of simka who wouldn't necessarily know how long is "too long" for a simka job.

**Comment by rchikhi** [comment]
I absolutely agree that it is problem. Thanks for the clarifications.

**Comment by nick-youngblut** [comment]
No problem! Since you closed this issue, does that mean that the issue has been fixed in the latest version of simka?

**Comment by rchikhi** [comment]
in the master branch yes, but not yet the release
