### ISSUE TITLE
Issues during linking stage

### ISSUE THREAD

**Issue by shayandoust** [GATB/simka#11]
Hello,

I am packaging simka as a debian package[1].

Cloning and compiling directly from source completes successfully. However, with regards to debian policy, gatb-core is already available as a debian package in the repository. A debian package library takes precedence over gatb-core being built with simka. As a result, I have made a patch[2] to which cmake is adapted to use the system available gatb-core instead of that in thirdparty. This seemingly brings up issues during the linking stage with SimkaAlgorithm.cpp[3].

I would be grateful if this patch is looked at or I am pointed into the correct path. I am unsure if gatb-core or some other cmake in gatb-core injects something into simka that causes a successful build.

Thanks,
Shayan Doust

[1]: https://salsa.debian.org/med-team/simka
[2]: https://salsa.debian.org/med-team/simka/blob/master/debian/patches/use_debian_packaged_libraries.patch
[3]: http://paste.debian.net/1099683/

**Comment by clemaitre** [comment]
Hi Shayan,

thank you for packaging simka!
I am not sure this is a good idea to use the debian package of gatb-core to install simka because the installed gatbcore package is probably not the good version for simka. In fact, all "gatb-tools" do not use the same version of gatb-core, which has quite evolved since its first release, sometimes this is not even a released one.
For instance, simka v1.5.1 is built upon gatb-core v1.2.2, and it will probably not compile with a more recent version of gatb-core. Could this explain the errors you obtain ?

Claire

**Comment by shayandoust** [comment]
Hello Claire,

Many thanks for your prompt reply.

It could well be the reason why it does not build successfully. I will do a fresh separate clone of the repository and force the latest version of gatb-core and see if I can reproduce this. If I get an identical error, I can rule this out as a version compatibility issue.

It is a bit confusing as to why the linker fails though. I would think that if anything, compilation should present some failures (maybe some API or ABI changes) as the linker only complains about "undefined reference to `SimkaAlgorithm<32ul>::SimkaAlgorithm(gatb::core::tools::misc::IProperties*)'". 

I will do a quick version experimentation and see if this is related.

Thanks,
Shayan Doust

**Comment by shayandoust** [comment]
An update:

Further inspection, I see that because template functions cannot entirely be written within cpp, gatb-core tries to work around this by using *.cpp.in files visible within simka. The gatb-core-klist variable was simply empty and did not generate these files, so I simply hardcoded "list (APPEND KSIZE_DEFAULT_LIST  32   64   96  128  160  192  224  256)" into as a patch and the binaries build successfully!

Thanks,
Shayan Doust
