### ISSUE TITLE
.fastq.gz support

### ISSUE THREAD

**Issue by jianshu93** [GATB/simka#14]
Hi, I run into this error via using this input (build from the latest version)

WP1310:  /condo/ieg/qiqi/Haibei_metaG/WP1310_paired_1.fastq.gz ; /condo/ieg/qiqi/Haibei_metaG/WP1310_paired_2.fastq.gz

the error is: ERROR: Can't open dataset: WP1310

Any idea why?

Testing ran successfully.

It takes me half a day to find out why. Support for fastq.gz is not ready?

Thanks,

Jianshu

**Comment by clemaitre** [comment]
Hi Jianshu,

Simka does support gzipped files, so the problem is probably somewhere else.

Have you verified the paths and user permissions of your files ?

Claire
