### ISSUE TITLE
multifasta file as input

### ISSUE THREAD

**Issue by lmanchon** [GATB/simka#27]
--Hi,

i have to compare a multifasta file (200000 sequences) with a chromosomic region. I have already done that with kmer-db tool (https://doi.org/10.1093/bioinformatics/bty610) and i need to compare the results of kmer-db with other tool such as simka.
But i don't find the correct command to do this.
Kmer-db compute a list of distances between each sequence of the multifasta file and the chromosomic region.

this is my input file:

simka_input.txt:
A: multifasta.fasta
B: chr1_region.fasta

the command line i used:
simka -in ./simka_input.txt -out ./simka_results/ -out-tmp ./simka_temp_output -max-memory 128000 -nb-cores 24

in the simka_results directory: zcat mat_abundance_jaccard.csv.gz
;A;B
A;0.000000;0.999993
B;0.999993;0.000000

i have only 2 values whereas i have 200000 sequences in my input file, i don't understand. it seems that simka concatenates all the sequences of the multifasta file and then compares with the other file. How to avoid that ?

thank you --

**Comment by clemaitre** [comment]
Hi, 

Simka is a tool designed for comparing raw read samples, and not individual sequences such as genomes. Therefore, all sequences in a multifasta file are considered belonging to the same entity to be compared. 
The only way I can see to compare your 200,000 sequences with Simka would be to split your multifasta file in 200,000 fasta files containing each only one sequence, which I agree is not very practical in your case.

Claire
