### ISSUE TITLE
Simka k-mers frequencies table

### ISSUE THREAD

**Issue by LDoni** [GATB/simka#28]
Hello :)
Thanks to maintain Simka!
Is it possible to obtain the k-mers table counts for each sample analyzed with Simka, to then use it in R to calculate alfa diversity metrics?
Thanks,
L

**Comment by clemaitre** [comment]
Hi,

by k-mers table counts, do you mean the "kmer spectrum", that is how many kmers are observed how many times in a given sample ?
If yes, Simka can not output this kind of file, but another GATB tool can do this : [DSK](https://github.com/GATB/dsk). You will have to run it separately for each sample with the `-histo 1` option to obtain a text file for each sample containing the kmer spectrum (two column table, with the multiplicity in first column and the number of kmers with this multiplicity in the second column).

Alternatively, you can also have a look at [kmtricks](https://github.com/tlemane/kmtricks) that can do many stuffs with kmers...

I hope it helps,
regards,
Claire

**Comment by LDoni** [comment]
Hello Claire  :)
Thanks for your quick and informative response.
I will try your suggestions.
I wish you the best,
L
