### ISSUE TITLE
Reuse simka merge data on subset of samples

### ISSUE THREAD

**Issue by Rridley7** [GATB/simka#30]
Hello, thanks for your work on this tool! I wanted to ask whether it was okay to reuse previous simka merge results on a subset of the data? Eg., I have already run simka on a large set of samples, if I rerun simka using the same temporary directory, but only pass a subset of the original files as the files of interest, will this give the correct distance metrics for this subset of samples?

**Comment by clemaitre** [comment]
Hi,

The distance between two samples does not depend on the presence/absence of other samples in the sample set. So if the samples you want to compare were all present in the initial large sample set, you do not need to re-run simka. You just need to extract the corresponding lines and columns of interest in the large distance matrix.

I hope this answers your question,
Regards,
Claire

**Comment by Rridley7** [comment]
This answers my question, thank you!
